---
- hosts: hypervisors
  tasks:

  - name: Install repos 
    dnf:
      name:
        - centos-release-advanced-virtualization.noarch

  - name: Install virtualization
    dnf:
      name:
      - libvirt-client.x86_64
      - libvirt-daemon-kvm.x86_64

  - systemd:
      name: libvirtd
      state: started
      enabled: true

  - command: ssh-keygen -t ed25519 -f /root/.ssh/id_ed25519 -N ''
    args:
      creates: /root/.ssh/id_ed25519

  - command: cat /root/.ssh/id_ed25519.pub
    check_mode: false
    register: ssh_pubkey

  - lineinfile:
      path: /root/.ssh/authorized_keys
      line: "{{ hostvars[item]['ssh_pubkey']['stdout'] }}"
    loop: "{{ groups['hypervisors'] }}"
